<div id="lc-banner" class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img src="img/1.jpg" alt="...">
                    <div class="carousel-caption">
                        yyyyyyyy
                    </div>
                </div>
                <div class="item">
                    <img src="img/2.jpg" alt="...">
                    <div class="carousel-caption">
                        gggggggg
                    </div>
                </div>
                <div class="item">
                    <img src="img/3.jpg" alt="...">
                    <div class="carousel-caption">
                        fffffffff
                    </div>
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>