<div id="lc-header" class="masthead" role="navigation">
    <h1 class="text-muted">
        <a href="/">XX 中学</a>
    </h1>

    <ul class="nav nav-justified">
        <li class="active lc-right-border">
            <a href="/">
                <span class="glyphicon glyphicon-home"></span>
                &nbsp;首  页
            </a>
        </li>
        <li class="lc-right-border">
            <a href="/">学校概况</a>
        </li>
        <li class="lc-right-border">
            <a href="/">师资建设</a>
        </li>
        <li class="lc-right-border">
            <a href="/">学习园地</a>
        </li>
        <li class="">
            <a href="/">其他板块</a>
        </li>
    </ul>
</div>

