<meta charset="UTF-8">
<title>XX 中学</title>
<meta name="description" content="description">
<link rel="shortcut icon" href="javascript:void(0);">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="author" content="">
<link rel="shortcut icon" href="javascript:void(0);">
<!-- <link rel="canonical" href="http://www.dxlisting.com"> -->
<link rel="robots" content="Index, Follow">